### PR TITLE
Add Github Action and GitPod

### PR DESCRIPTION
**Pull request by LinuxSuRen**
/cc @kubesphere/sig-devops

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
It works well, please see also the PR from my personal repository.

https://github.com/LinuxSuRen/s2irun/pull/2

**Comment by LinuxSuRen** [comment]
hi @JohnNiang , we don't have an active owner. So, this PR #31 should be the upstream of the current one.

**Comment by JohnNiang** [comment]
> hi @JohnNiang , we don't have an active owner. So, this PR #31 should be the upstream of the current one.

Thanks for your reminder.

**Comment by LinuxSuRen** [comment]
In order to make this OWNER file works. I'm going to close and reopen this PR.

**Pull request merged**
